import { Psychiatrist, Review, Booking, Complaint, PlatformSettings, PatientAccount } from './types';

export const initialPlatformSettings: PlatformSettings = {
  commissionRate: 18,
  maxBoostedDoctors: 9,
};

export const initialPsychiatrists: Psychiatrist[] = [
  {
    id: 'doc-1',
    name: 'Dr. Ananda Wickramasinghe',
    title: 'Senior Consultant Psychiatrist',
    slmcRegNo: 'SLMC-38491',
    status: 'approved',
    isBoosted: true,
    boostTier: '3-day',
    boostExpiry: '2026-08-16T23:59:59Z',
    photo: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?q=80&w=600&auto=format&fit=crop',
    bio: 'Over 16 years of clinical experience in mood disorders, anxiety, and adult cognitive behavioral therapy across Sri Lanka teaching hospitals.',
    languages: ['English', 'Sinhala'],
    sessionFormats: ['Video Telehealth', 'Audio Call'],
    specialties: ['Depression & Anxiety', 'Bipolar Disorder', 'Stress Management'],
    district: 'Colombo',
    feeLkr: 6000,
    rating: 4.9,
    reviewCount: 42,
    ratingDistribution: { 5: 38, 4: 3, 3: 1, 2: 0, 1: 0 },
    upcomingSlots: [
      { id: 's101', datetime: '2026-08-14T09:00:00Z', durationMins: 45, status: 'available' },
      { id: 's102', datetime: '2026-08-14T10:30:00Z', durationMins: 45, status: 'available' },
      { id: 's103', datetime: '2026-08-15T14:00:00Z', durationMins: 45, status: 'available' },
      { id: 's104', datetime: '2026-08-16T11:00:00Z', durationMins: 45, status: 'available' },
    ],
    documents: [
      { id: 'd1', name: 'SLMC_Board_Certificate_2010.pdf', url: '#', uploadDate: '2024-01-15', status: 'Approved' },
      { id: 'd2', name: 'MBBS_Peradeniya_Degree.pdf', url: '#', uploadDate: '2024-01-15', status: 'Approved' },
    ],
  },
  {
    id: 'doc-2',
    name: 'Dr. Nilakshi Samarasinghe',
    title: 'Child & Adolescent Psychiatrist',
    slmcRegNo: 'SLMC-42109',
    status: 'approved',
    isBoosted: true,
    boostTier: '1-day',
    boostExpiry: '2026-08-13T23:59:59Z',
    photo: 'https://images.unsplash.com/photo-1594824813566-78a1ed6a2b4b?q=80&w=600&auto=format&fit=crop',
    bio: 'Dedicated to young minds and neurodevelopmental care. Specialist in ADHD, teen anxiety, and family relational dynamics.',
    languages: ['English', 'Sinhala'],
    sessionFormats: ['Video Telehealth'],
    specialties: ['Child & Adolescent', 'ADHD Care', 'Family Therapy'],
    district: 'Kandy',
    feeLkr: 5500,
    rating: 4.85,
    reviewCount: 31,
    ratingDistribution: { 5: 27, 4: 3, 3: 1, 2: 0, 1: 0 },
    upcomingSlots: [
      { id: 's201', datetime: '2026-08-13T16:00:00Z', durationMins: 45, status: 'available' },
      { id: 's202', datetime: '2026-08-14T15:00:00Z', durationMins: 45, status: 'available' },
      { id: 's203', datetime: '2026-08-16T10:00:00Z', durationMins: 45, status: 'available' },
    ],
    documents: [
      { id: 'd3', name: 'SLMC_Reg_Doc_ChildPsych.pdf', url: '#', uploadDate: '2024-03-10', status: 'Approved' },
    ],
  },
  {
    id: 'doc-3',
    name: 'Dr. Kiruba Sathananthan',
    title: 'Consultant Neuropsychiatrist',
    slmcRegNo: 'SLMC-29018',
    status: 'approved',
    isBoosted: true,
    boostTier: '3-day',
    boostExpiry: '2026-08-16T23:59:59Z',
    photo: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?q=80&w=600&auto=format&fit=crop',
    bio: 'Pioneer in trauma-informed care and geriatric psychiatry. Fluent in Tamil, Sinhala, and English with compassionate tele-consultations.',
    languages: ['English', 'Tamil', 'Sinhala'],
    sessionFormats: ['Video Telehealth', 'Audio Call'],
    specialties: ['PTSD & Trauma', 'Geriatric Psychiatry', 'Insomnia & Sleep'],
    district: 'Jaffna',
    feeLkr: 5000,
    rating: 5.0,
    reviewCount: 28,
    ratingDistribution: { 5: 28, 4: 0, 3: 0, 2: 0, 1: 0 },
    upcomingSlots: [
      { id: 's301', datetime: '2026-08-14T11:00:00Z', durationMins: 45, status: 'available' },
      { id: 's302', datetime: '2026-08-15T17:00:00Z', durationMins: 45, status: 'available' },
    ],
    documents: [
      { id: 'd4', name: 'Jaffna_General_SLMC.pdf', url: '#', uploadDate: '2023-11-20', status: 'Approved' },
    ],
  },
  {
    id: 'doc-4',
    name: 'Dr. Chaminda Perera',
    title: 'Consultant Addiction Psychiatrist',
    slmcRegNo: 'SLMC-51022',
    status: 'approved',
    isBoosted: false,
    boostTier: 'none',
    boostExpiry: null,
    photo: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?q=80&w=600&auto=format&fit=crop',
    bio: 'Specializing in substance recovery, behavioral addictions, and burnout among working professionals.',
    languages: ['English', 'Sinhala'],
    sessionFormats: ['Video Telehealth', 'Chat Consultation'],
    specialties: ['Addiction Recovery', 'Workplace Burnout', 'OCD & Panic'],
    district: 'Galle',
    feeLkr: 4800,
    rating: 4.7,
    reviewCount: 19,
    ratingDistribution: { 5: 15, 4: 3, 3: 1, 2: 0, 1: 0 },
    upcomingSlots: [
      { id: 's401', datetime: '2026-08-14T18:00:00Z', durationMins: 45, status: 'available' },
      { id: 's402', datetime: '2026-08-16T15:30:00Z', durationMins: 45, status: 'available' },
    ],
    documents: [
      { id: 'd5', name: 'SLMC_Cert_Galle.pdf', url: '#', uploadDate: '2024-05-02', status: 'Approved' },
    ],
  },
  {
    id: 'doc-5',
    name: 'Dr. Thilini Rajapaksha',
    title: 'Consultant Women’s Mental Health Specialist',
    slmcRegNo: 'SLMC-48119',
    status: 'approved',
    isBoosted: false,
    boostTier: 'none',
    boostExpiry: null,
    photo: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?q=80&w=600&auto=format&fit=crop',
    bio: 'Focusing on perinatal mood disorders, postpartum wellness, and hormonal mental health challenges.',
    languages: ['English', 'Sinhala'],
    sessionFormats: ['Video Telehealth'],
    specialties: ['Perinatal Depression', 'Women’s Health', 'Anxiety & Panic'],
    district: 'Kurunegala',
    feeLkr: 5200,
    rating: 4.92,
    reviewCount: 24,
    ratingDistribution: { 5: 22, 4: 2, 3: 0, 2: 0, 1: 0 },
    upcomingSlots: [
      { id: 's501', datetime: '2026-08-13T18:00:00Z', durationMins: 45, status: 'available' },
      { id: 's502', datetime: '2026-08-15T09:30:00Z', durationMins: 45, status: 'available' },
    ],
    documents: [
      { id: 'd6', name: 'SLMC_Perinatal_Creds.pdf', url: '#', uploadDate: '2024-04-18', status: 'Approved' },
    ],
  },
  {
    id: 'doc-6',
    name: 'Dr. Ruwan Gunawardena',
    title: 'Adult Psychiatry Specialist',
    slmcRegNo: 'SLMC-55920',
    status: 'pending',
    isBoosted: false,
    boostTier: 'none',
    boostExpiry: null,
    photo: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?q=80&w=600&auto=format&fit=crop',
    bio: 'Recently submitted credential verification for online consultation on PsyNova platform.',
    languages: ['English', 'Sinhala'],
    sessionFormats: ['Video Telehealth'],
    specialties: ['General Adult Psychiatry', 'Depression'],
    district: 'Gampaha',
    feeLkr: 4500,
    rating: 0,
    reviewCount: 0,
    ratingDistribution: { 5: 0, 4: 0, 3: 0, 2: 0, 1: 0 },
    upcomingSlots: [],
    documents: [
      { id: 'd7', name: 'SLMC_Pending_Verification_2026.pdf', url: '#', uploadDate: '2026-08-01', status: 'Pending' },
    ],
  },
];

export const initialReviews: Review[] = [];

export const initialBookings: Booking[] = [];

export const initialComplaints: Complaint[] = [];

export const initialPatients: PatientAccount[] = [];
